# Generated by Django 2.2.15 on 2022-01-08 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20220107_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='date_joined',
            field=models.DateField(blank=True, null=True, verbose_name='Date of joining'),
        ),
    ]
