# Generated by Django 2.2.15 on 2022-01-08 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20220108_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='date_joined',
            field=models.DateField(null=True, verbose_name='Date of joining'),
        ),
    ]
