# Generated by Django 2.2.15 on 2022-01-19 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20220108_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='gender',
            field=models.CharField(blank=True, choices=[(None, 'Sex:'), ('Male', 'M'), ('Female', 'F')], max_length=6, null=True, verbose_name='Gender(M/F)'),
        ),
    ]
