# Generated by Django 2.2.15 on 2022-01-26 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20220126_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='post',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Post applied for'),
        ),
    ]
