# Generated by Django 2.2.15 on 2022-01-26 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_account_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='from_dsg',
            field=models.CharField(blank=True, choices=[(None, 'Select Posts'), ('Stage 1', 'Assistant Prof. (Stage 1)'), ('Stage 2', 'Assistant Prof. (Stage 2)'), ('Stage 3', 'Assistant Prof. (Stage 3)'), ('Stage 4', 'Associate Prof. (Stage 4)')], max_length=30, null=True, verbose_name='From stage/desgn.'),
        ),
        migrations.AddField(
            model_name='account',
            name='to_dsg',
            field=models.CharField(blank=True, choices=[(None, 'Select Posts'), ('Stage 1', 'Assistant Prof. (Stage 2)'), ('Stage 2', 'Assistant Prof. (Stage 3)'), ('Stage 3', 'Associate Prof. (Stage 4)'), ('Stage 4', 'Professor (Stage 5)')], max_length=30, null=True, verbose_name='To stage/desgn.'),
        ),
        migrations.AlterField(
            model_name='account',
            name='gender',
            field=models.CharField(blank=True, choices=[(None, 'Select'), ('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=6, null=True, verbose_name='Gender(M/F)'),
        ),
        migrations.AlterField(
            model_name='account',
            name='post',
            field=models.CharField(blank=True, choices=[(None, 'Select Posts'), ('Stage 2', 'Assistant Prof. (Stage 2)'), ('Stage 3', 'Assistant Prof. (Stage 3)'), ('Stage 4', 'Associate Prof. (Stage 4)'), ('Stage 5', 'Professor (Stage 5)')], max_length=30, null=True, verbose_name='Post applied for'),
        ),
    ]
