# Generated by Django 2.2.15 on 2022-01-27 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_auto_20220127_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='created',
        ),
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
