# Generated by Django 2.2.15 on 2022-01-27 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_auto_20220127_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='Designation',
            field=models.CharField(blank=True, choices=[(None, 'Select'), ('dsg-1', 'Assistant Professor'), ('dsg-2', 'Associate Professor')], max_length=30, null=True),
        ),
    ]
