# Generated by Django 2.2.15 on 2022-01-29 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_auto_20220127_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='addr_corres',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Address for corres'),
        ),
        migrations.AddField(
            model_name='account',
            name='addr_perm',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Address for permanent'),
        ),
        migrations.AddField(
            model_name='account',
            name='agp',
            field=models.IntegerField(choices=[(None, 'Select'), (1, '6000'), (2, '7000'), (3, '8000'), (4, '9000'), (5, '10000')], null=True, verbose_name='AGP fig.'),
        ),
        migrations.AddField(
            model_name='account',
            name='catg',
            field=models.CharField(blank=True, choices=[(None, 'Select'), ('cast-1', 'SC'), ('cast-2', 'ST'), ('cast-3', 'OBC-A'), ('cast-4', 'OBC-B'), ('cast-5', 'GEN')], max_length=6, null=True, verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='account',
            name='current_dsg',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Present Dsgn.'),
        ),
        migrations.AddField(
            model_name='account',
            name='dt_eligibility',
            field=models.DateField(null=True, verbose_name='Date of last pronotion'),
        ),
        migrations.AddField(
            model_name='account',
            name='dt_last_promo',
            field=models.DateField(null=True, verbose_name='Date of last pronotion'),
        ),
        migrations.AddField(
            model_name='account',
            name='mobile',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='parent',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
