# Generated by Django 2.2.15 on 2022-01-31 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_auto_20220129_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_carry',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='mobile',
            field=models.CharField(blank=True, default='Individual', max_length=10, null=True),
        ),
    ]
