# Generated by Django 2.2.15 on 2022-02-01 07:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_auto_20220131_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='addr_perm',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Address for permanent'),
        ),
        migrations.AlterField(
            model_name='account',
            name='dt_eligibility',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date of promo elig'),
            preserve_default=False,
        ),
    ]
